<!DOCTYPE html>
<html>
<head>
	<title><?=APP_NAME?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
 	<link href="<?=HTTP.WWW_ROOT?>/lib/bootstrap/css/bootstrap.css" rel="stylesheet">
	<link href="<?=HTTP.WWW_ROOT?>/lib/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
	
	<script type="text/javascript" src="<?php echo HTTP.WWW_ROOT?>/lib/bootstrap/js/bootstrap.js"></script>
		
	<link href='http://fonts.googleapis.com/css?family=Bevan' rel='stylesheet' type='text/css'>
	<link href="<?=HTTP.WWW_ROOT?>/lib/bootstrap/css/custom.css" rel="stylesheet">
		
</head><body>

<div class="container-fluid">
	<div class='row-fluid'>
		<div class='span12'>
			
			<div class='span4' >
				<span class='brand'><a href='<?=HTTP.WWW_ROOT?>'>ASE</a><span style='color:#b73c36'>T5</span></span></span>
			</div>

			
	</div>
	</div>
	
	<div class="row-fluid">
		<div class="span12">
			<?php
				echo $this->layout()->content;	
			?>			
		</div><!--/span-->
	</div><!--/row-->
	
	<div class='row-fluid'>
		<hr>
	</div>
	
	<div class='row-fluid center footer-links'>
	</div>
		
	<footer class='center'>
		<p style='color:#ababab;font-size:11px;letter-spacing:1px;'>University of Sussex. Advance Computer Science, T5.</p>
	</footer>

</div><!--/.fluid-container-->

</body>

</script>
</html>