<div class='row-fluid'>

	<div class='span4'>
		<img src='<?=HTTP.WWW_ROOT?>/res/img/512/package_code_512.png'>
	</div>
	<div class='span8'>
	
		<h1>
			With A <span class='blue'>ProjectPackets</span> you can kickoff your project in minutes. 
		</h1>
		<hr>
		
		<div class='center'>
			<h2 class='blue'> For Everyone. For Free. Forever.</h2>
		</div>
		
		<div class='row-fluid'>
		
			<div class='span12 white-panel'>
				<p>You will find ProjectPackets of various Frameworks and Domains. Roadmap include building Packets for - ERP, CRM, HRM, Quiz, e-Commerce, Management Tools, School Management, College Management, E-learning, Blog, Real Estate, Business Directory, Restaurant Owners, Social Networking, Inventory Management, and much more. Feel free to request the one you need. <br><br>Currently we are working only on PHP Packets using Zend, Yii, Symfony, Qcodo, CakePhp and Core PHP.
				</p>
				<br>
				<a href='<?=HTTP.WWW_ROOT?>/page/all-about-project-packets' class='btn pull-right btn-info'>Why ProjectPacket? <i class='icon-chevron-right'></i></a>
			</div>
			
		</div>
	
		<div class='span1'>
			
		</div>
	
	</div>
</div>

